ren "src\app\page.tsx" page.page.tsx
ren "src\app\chat\[branchId]\page.tsx" page.page.tsx
ren "src\app\conversation\[conversationId]\page.tsx" page.page.tsx
ren "src\app\layout.tsx" layout.layout.tsx
ren "src\app\api\analytics\route.ts" route.route.ts
ren "src\app\api\auth\[...nextauth]\route.ts" route.route.ts
ren "src\app\api\auth\signup\route.ts" route.route.ts
ren "src\app\api\branches\create\route.ts" route.route.ts
ren "src\app\api\branches\feedback\route.ts" route.route.ts
ren "src\app\api\branches\merge\route.ts" route.route.ts
ren "src\app\api\branches\promote\route.ts" route.route.ts
ren "src\app\api\branches\replay\route.ts" route.route.ts
ren "src\app\api\branches\suggest\route.ts" route.route.ts
ren "src\app\api\conversations\[id]\route.ts" route.route.ts
ren "src\app\api\conversations\route.ts" route.route.ts
ren "src\app\api\memory\context\route.ts" route.route.ts
ren "src\app\api\memory\extract\route.ts" route.route.ts
ren "src\app\api\memory\inherit\route.ts" route.route.ts
ren "src\app\api\memory\promote\route.ts" route.route.ts
ren "src\app\api\memory\route.ts" route.route.ts
